CREATE TABLE [dbo].[line_validation_suggestion] (

	[selection_GUID] varchar(50) NULL, 
	[GUID] varchar(50) NULL, 
	[run_id] varchar(40) NULL, 
	[master_table_GUID] varchar(50) NULL, 
	[table_name] varchar(50) NULL, 
	[table_type] varchar(50) NULL, 
	[column_name] varchar(200) NULL, 
	[ai_column_name] varchar(200) NULL, 
	[index_key] varchar(200) NULL, 
	[validation_rule_id] int NULL, 
	[validation_rule] varchar(300) NULL, 
	[business_rule_name] varchar(500) NULL, 
	[ai_reasoning] varchar(2000) NULL, 
	[simplicity] varchar(200) NULL, 
	[condition] varchar(2000) NULL, 
	[minimum_range] float NULL, 
	[maximum_range] float NULL, 
	[minimum_date_range] date NULL, 
	[maximum_date_range] date NULL, 
	[sql] varchar(4000) NULL, 
	[sample_data] varchar(4000) NULL, 
	[source_system] varchar(20) NULL, 
	[workspace_name] varchar(200) NULL, 
	[database_name] varchar(200) NULL, 
	[selected] int NULL, 
	[status] varchar(50) NOT NULL, 
	[created_by] varchar(50) NOT NULL, 
	[created_on] varchar(50) NOT NULL, 
	[modified_by] varchar(50) NOT NULL, 
	[modified_on] varchar(50) NOT NULL
);